podTemplate(label: 'docker-build',
  containers: [
    containerTemplate(
      name: 'git',
      image: 'alpine/git',
      command: 'cat',
      ttyEnabled: true
    ),
    containerTemplate(
      name: 'docker',
      image: 'docker',
      command: 'cat',
      ttyEnabled: true
    ),
  ],
  volumes: [
    hostPathVolume(mountPath: '/var/run/docker.sock', hostPath: '/var/run/docker.sock'),
  ]
) {
    node('docker-build') {
        def dockerHubCred = docker_hub_cred
        def appImage

        stage('Checkout'){
            container('git'){
                checkout scm
            }
        }

        stage('Gradle Build') {
          steps {
            sh 'gradle clean build -x test build.gradle'
          }
        }

        stage('Build'){
            container('docker'){
                script {
                    appImage = docker.build("psawesome/xyz-cheese-web")
                }
            }
        }

        stage('Push'){
            container('docker'){
                script {
                    docker.withRegistry('https://registry.hub.docker.com', dockerHubCred){
                        appImage.push("${env.BUILD_NUMBER}")
                        appImage.push("latest")
                    }
                }
            }
        }
    }

}